const translations = {
        ar: {
                langLabel: "Français",
                        share: "مشاركة",
                                eidTitle: "عيد مبارك سعيد",
                                        eidSub: "كل عام وأنتم بخير",
                                                eidCard: "تقبل الله منا ومنكم",
                                                        nextRamadan: "نراكم في رمضان القادم",
                                                                year: "1448 هـ - 2027"
                                                                    },
                                                                        fr: {
                                                                                langLabel: "العربية",
                                                                                        share: "Partager",
                                                                                                eidTitle: "Aïd Moubarak",
                                                                                                        eidSub: "Meilleurs vœux",
                                                                                                                eidCard: "Qu'Allah accepte vos œuvres",
                                                                                                                        nextRamadan: "À l'année prochaine",
                                                                                                                                year: "1448 AH - 2027"
                                                                                                                                    }
                                                                                                                                    };

                                                                                                                                    let currentLang = 'ar';

                                                                                                                                    function updateUI() {
                                                                                                                                        const now = new Date();
                                                                                                                                            const targetDate = new Date('2026-03-22T23:59:00');
                                                                                                                                                const t = translations[currentLang];

                                                                                                                                                    document.getElementById('langLabel').innerText = t.langLabel;
                                                                                                                                                        document.getElementById('shareText').innerText = t.share;

                                                                                                                                                            const contentArea = document.getElementById('content-area');

                                                                                                                                                                if (now > targetDate) {
                                                                                                                                                                        contentArea.innerHTML = `
                                                                                                                                                                                    <h1 style="color: #f77062">${t.nextRamadan}</h1>
                                                                                                                                                                                                <div class="highlight-box">${t.year}</div>
                                                                                                                                                                                                        `;
                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                    contentArea.innerHTML = `
                                                                                                                                                                                                                                <h1 style="color: #f77062">${t.eidTitle}</h1>
                                                                                                                                                                                                                                            <p style="color: #888">${t.eidSub}</p>
                                                                                                                                                                                                                                                        <div class="highlight-box">${t.eidCard}</div>
                                                                                                                                                                                                                                                                `;
                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                    // تبديل اللغة
                                                                                                                                                                                                                                                                    document.getElementById('langBtn').onclick = () => {
                                                                                                                                                                                                                                                                        currentLang = currentLang === 'ar' ? 'fr' : 'ar';
                                                                                                                                                                                                                                                                            document.body.dir = currentLang === 'ar' ? 'rtl' : 'ltr';
                                                                                                                                                                                                                                                                                updateUI();
                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                // مشاركة
                                                                                                                                                                                                                                                                                document.getElementById('shareBtn').onclick = async () => {
                                                                                                                                                                                                                                                                                    if (navigator.share) {
                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                        await navigator.share({ title: 'تهنئة العيد', url: window.location.href });
                                                                                                                                                                                                                                                                                                                } catch (err) { console.log("Error sharing"); }
                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                            alert("المشاركة غير مدعومة في متصفحك حالياً");
                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                // وظيفة الألعاب النارية والقصاصات
                                                                                                                                                                                                                                                                                                                                function startCelebration() {
                                                                                                                                                                                                                                                                                                                                    const confettiContainer = document.getElementById('confetti-container');
                                                                                                                                                                                                                                                                                                                                        const fireworksContainer = document.getElementById('fireworks-container');
                                                                                                                                                                                                                                                                                                                                            const colors = ['#f77062', '#c5a059', '#e3f2fd', '#ffeb3b'];

                                                                                                                                                                                                                                                                                                                                                // القصاصات
                                                                                                                                                                                                                                                                                                                                                    for (let i = 0; i < 100; i++) {
                                                                                                                                                                                                                                                                                                                                                            const p = document.createElement('div');
                                                                                                                                                                                                                                                                                                                                                                    p.className = 'confetti-piece';
                                                                                                                                                                                                                                                                                                                                                                            p.style.left = Math.random() * 100 + '%';
                                                                                                                                                                                                                                                                                                                                                                                    p.style.backgroundColor = colors[Math.floor(Math.random() * colors.length)];
                                                                                                                                                                                                                                                                                                                                                                                            p.style.animationDuration = (Math.random() * 3 + 2) + 's';
                                                                                                                                                                                                                                                                                                                                                                                                    p.style.animationDelay = Math.random() * 2 + 's';
                                                                                                                                                                                                                                                                                                                                                                                                            confettiContainer.appendChild(p);
                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                    // الألعاب النارية (تظهر كل فترة)
                                                                                                                                                                                                                                                                                                                                                                                                                        setInterval(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                const s = document.createElement('div');
                                                                                                                                                                                                                                                                                                                                                                                                                                        s.className = 'firework-spark';
                                                                                                                                                                                                                                                                                                                                                                                                                                                s.style.left = Math.random() * 100 + '%';
                                                                                                                                                                                                                                                                                                                                                                                                                                                        s.style.top = Math.random() * 100 + '%';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                s.style.backgroundColor = colors[Math.floor(Math.random() * colors.length)];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fireworksContainer.appendChild(s);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setTimeout(() => s.remove(), 1000);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }, 500);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // التشغيل
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    updateUI();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    startCelebration();
}